[package]
name = "digits"
version = "0.1.0"
authors = ["Kasper Nielsen <kasper0406@gmail.com>"]

[dependencies]
num = "*"
rand = "*"
futures-preview = "*"
crossbeam = "0.4"
rayon = "1.0"
num_cpus = "1.8.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
